import { PageHeader } from "@/components/dashboard/page-header"
import { StatCard } from "@/components/analytics/stat-card"
import { MessageVolumeChart } from "@/components/analytics/message-volume-chart"
import { ChannelDistributionChart } from "@/components/analytics/channel-distribution-chart"
import { RulePerformanceChart } from "@/components/analytics/rule-performance-chart"
import { getAnalyticsData } from "@/lib/analytics/queries"
import { MessageSquare, Bot, Zap, Clock } from "lucide-react"

export default async function AnalyticsPage() {
  const data = await getAnalyticsData()

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Analytics"
        description="Track your messaging performance and automation metrics"
      />

      {/* Key Metrics */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatCard
          title="Total Messages"
          value={data.totalMessages.toLocaleString()}
          description={`${data.messagesReceived} received, ${data.messagesSent} sent`}
          icon={MessageSquare}
        />
        <StatCard
          title="AI-Assisted Replies"
          value={`${data.aiAssistedPercentage}%`}
          description={`${data.aiAssistedReplies} suggestions used`}
          icon={Bot}
        />
        <StatCard
          title="Automated Replies"
          value={`${data.automatedPercentage}%`}
          description={`${data.automatedReplies} auto-generated by rules`}
          icon={Zap}
        />
        <StatCard
          title="Avg Response Time"
          value={data.averageResponseTimeFormatted}
          description="Time to first reply"
          icon={Clock}
        />
      </div>

      {/* Charts */}
      <div className="grid gap-6 lg:grid-cols-2">
        <MessageVolumeChart data={data.messagesByDay} />
        <ChannelDistributionChart data={data.messagesByChannel} />
      </div>

      {/* Rule Performance */}
      <RulePerformanceChart data={data.rulePerformance} />
    </div>
  )
}
